### ISSUE TITLE
[PE-D][Tester E] Character in greeting unsupported by Windows

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-4/tp#145]
On Windows Command Prompt, launching the .jar prints a welcome message with unsupported symbol: `ı`. This symbol is replaced with a question mark `?` in the console.
![image.png](https://raw.githubusercontent.com/malcolmang/ped/main/files/47757581-2ae1-4c1b-b3c6-7711374c8f46.png)

-------------
Labels: `type.FunctionalityBug` `severity.VeryLow`
original: malcolmang/ped#1

**Comment by dhanish265** [comment]
Duplicate issue of #156
