### ISSUE TITLE
Modifying a patient’s prescription: edit

### ISSUE THREAD

**Issue by RiaVora** [AY2223S1-CS2113-F11-4/tp#15]
As a doctor, I wish to modify prescription details to correct any errors made during a previous prescription

<img width="546" alt="image" src="https://user-images.githubusercontent.com/31297758/193443130-c6ba0b9e-8a25-4576-afdb-d983ec845227.png">

**Comment by kaseykwok** [comment]
Format changes to: `edit i/index [n/medicine_name] [d/medicine_dosage] [t/time_interval]`
