### ISSUE TITLE
[PE-D][Tester C] Able to add invalid dates when adding patient

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-4/tp#153]
![image.png](https://raw.githubusercontent.com/jjtoh/ped/main/files/acdafbc2-9097-42da-a655-a1858e458720.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jjtoh/ped#2

**Comment by kaseykwok** [comment]
Will be fixed through #117
