### ISSUE TITLE
[PE-D][Tester A] Invalid date can pass the check

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-4/tp#165]
I knew that's a bit nit-picking, but obvious invalid date can pass the check(e.g.99-99-2001)

![p3.png](https://raw.githubusercontent.com/AmethystQ/ped/main/files/609f8731-8991-4fb8-b69f-120611d9a9dd.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: AmethystQ/ped#2

**Comment by kaseykwok** [comment]
Will be fixed through #117
