### ISSUE TITLE
[PE-D][Tester A] There seems to have no way to delete a patient, a visit or delete a presciption

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2113-F11-4/tp#177]
There seems to have no way to delete a patient, a visit or delete a presciption(can only deactivate a prescription) so I cannot undo my operation if I input something wrong

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: AmethystQ/ped#5

**Comment by kaseykwok** [comment]
It is done on purpose that they can't be deleted.
