### ISSUE TITLE
[PE-D][Tester C] Extra line printed when retrieving a non-existent patient

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-4/tp#182]
This does not occur for the other retrieving features

![image.png](https://raw.githubusercontent.com/jjtoh/ped/main/files/719c1165-b6b9-490d-9c5f-158b6d48f499.png)

-------------
Labels: `severity.VeryLow` `type.FunctionalityBug`
original: jjtoh/ped#7

**Comment by dhanish265** [comment]
Non-issue. There appears to be an extra line because the character used to print is an underscore.
