### ISSUE TITLE
[PE-D][Tester C] Wrong error message when viewing visits by id

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2113-F11-4/tp#183]
![image.png](https://raw.githubusercontent.com/jjtoh/ped/main/files/c1081e03-f043-4e86-ba02-aadd15236173.png)

Patient definitely exists, perhaps the error should be stated as that patient has no visits.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: jjtoh/ped#8

**Comment by kaseykwok** [comment]
Reconfirm with the original bug report that it is a false bug.
