### ISSUE TITLE
[TA DG Review]

### ISSUE THREAD

**Issue by sevenseasofbri** [AY2223S1-CS2113-F11-4/tp#193]
The DG is good but can be more comprehensive. As a programmer, one would want enough information about the code they are contributing to. See https://se-education.org/addressbook-level3/DeveloperGuide.html as a good reference. Some of my comments on the DG (might repeat with points made in class):
- [x] Add intro, computer setup
- [x] The sequence diagram in PatientList Component is quite huge. Might want to reduce the size by omitting stuff or resizing
- [x]  A table of contents would be nice, to navigate
- [x] I only see sequence and class diagrams, consider adding an object diagram in an appropriate place

**Comment by RiaVora** [comment]
separated into relevant PRs
