### ISSUE TITLE
[Developer Guide] Non-functional requirement

### ISSUE THREAD

**Issue by kaseykwok** [AY2223S1-CS2113-F11-4/tp#222]

**Comment by RiaVora** [comment]
Example: 
Non-Functional Requirements
Should work on any mainstream OS as long as it has Java 11 or above installed.
Should be able to hold up to 1000 persons without a noticeable sluggishness in performance for typical usage.
A user with above average typing speed for regular English text (i.e. not code, not system admin commands) should be able to accomplish most of the tasks faster using commands than using the mouse.
{More to be added}

**Comment by RiaVora** [comment]
also add link for ip into developer guide
